export { default as Hero } from "./Hero";
export { default as ProofState } from "./ProofState";
export { default as Features } from "./Features";
export { default as Products } from "./Products";
export { default as Business } from "./Business";
export { default as Clients } from "./Clients";
export { default as ProofCompany } from "./ProofCompany";
export { default as Services } from "./Services";
export { default as Footer } from "./Footer";
